#!/bin/sh
# postinst script for parallel-launcher
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)
    if which xdg-mime > /dev/null; then
        xdg-mime install /usr/share/mime/packages/bps-mime.xml || true
        xdg-mime default ca.parallel_launcher.ParallelLauncher.desktop x-scheme-handler/rhdc || true
    fi
    if which update-desktop-database > /dev/null; then
        update-desktop-database -q || true
    fi
    if which xdg-desktop-menu > /dev/null; then
        xdg-desktop-menu forceupdate || true
    fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
